/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.OrderService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.UserService;
import javax.swing.JFrame;

/**
 *
 * @author usuario
 */
public class DashBoardGUI extends javax.swing.JFrame {

    ProductService productService;
    CategoryService categoryService;
    OrderService orderService;
    UserService userService;
    JFrame previusFrame;
    /**
     * Creates new form DashBoardGUI
     */
    public DashBoardGUI(CategoryService categoryService,ProductService productService, OrderService orderService,
        UserService userService,JFrame previusFrame) {
        initComponents();
        setSize(1000, 500);
        setLocationRelativeTo(null);
        this.productService = productService;
        this.categoryService=categoryService;
        this.orderService = orderService;
        this.userService = userService;
        this.previusFrame = previusFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPnlBackground = new javax.swing.JPanel();
        jPnlTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPnlCentral = new javax.swing.JPanel();
        jBtnGestionProductos = new javax.swing.JButton();
        jBtnGestionPedidos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPnlBotton = new javax.swing.JPanel();
        jBtnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 500));

        jPnlBackground.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPnlBackground.setLayout(new java.awt.BorderLayout());

        jPnlTop.setPreferredSize(new java.awt.Dimension(318, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione una opción:");

        javax.swing.GroupLayout jPnlTopLayout = new javax.swing.GroupLayout(jPnlTop);
        jPnlTop.setLayout(jPnlTopLayout);
        jPnlTopLayout.setHorizontalGroup(
            jPnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTopLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(484, 484, 484))
        );
        jPnlTopLayout.setVerticalGroup(
            jPnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlTopLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnlBackground.add(jPnlTop, java.awt.BorderLayout.PAGE_START);

        jPnlCentral.setLayout(new java.awt.GridBagLayout());

        jBtnGestionProductos.setText("Gestionar productos");
        jBtnGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionProductosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPnlCentral.add(jBtnGestionProductos, gridBagConstraints);

        jBtnGestionPedidos.setText("Gestionar pedidos");
        jBtnGestionPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionPedidosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPnlCentral.add(jBtnGestionPedidos, gridBagConstraints);

        jButton3.setText("Gestionar usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.ipady = 25;
        jPnlCentral.add(jButton3, gridBagConstraints);

        jPnlBackground.add(jPnlCentral, java.awt.BorderLayout.CENTER);

        jPnlBotton.setLayout(new java.awt.BorderLayout());

        jBtnCerrarSesion.setText("Cerrar sesión");
        jBtnCerrarSesion.setPreferredSize(new java.awt.Dimension(200, 48));
        jBtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarSesionActionPerformed(evt);
            }
        });
        jPnlBotton.add(jBtnCerrarSesion, java.awt.BorderLayout.LINE_END);

        jPnlBackground.add(jPnlBotton, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionActionPerformed
        previusFrame.setVisible(true);
        previusFrame.toFront(); // Traer el MainFrame al frente
        previusFrame.requestFocus(); // Pedir el enfoque para el MainFrame
        // Cerrar el SecondFrame
        dispose();
    }//GEN-LAST:event_jBtnCerrarSesionActionPerformed

    private void jBtnGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionProductosActionPerformed
        this.setVisible(false);
        GestionProductosGUI frame = new GestionProductosGUI(categoryService,productService,this);
        frame.setVisible(true);
    }//GEN-LAST:event_jBtnGestionProductosActionPerformed

    private void jBtnGestionPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionPedidosActionPerformed
        OrdenInfoGUI frame = new OrdenInfoGUI(orderService);
        frame.setVisible(true);
    }//GEN-LAST:event_jBtnGestionPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrarSesion;
    private javax.swing.JButton jBtnGestionPedidos;
    private javax.swing.JButton jBtnGestionProductos;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlBackground;
    private javax.swing.JPanel jPnlBotton;
    private javax.swing.JPanel jPnlCentral;
    private javax.swing.JPanel jPnlTop;
    // End of variables declaration//GEN-END:variables
}
