/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import co.com.hyunseda.market.entities.Product;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.OrderService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.UserService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class GestionProductosGUI extends javax.swing.JFrame {

    ProductService productService;
    CategoryService categoryService;
    JFrame previusFrame;
    private List<Product> products;
    public GestionProductosGUI(CategoryService categoryService,ProductService productService,JFrame previusFrame) {
        initComponents();
        setSize(1000, 500);
        setLocationRelativeTo(null);
        this.productService = productService;
        this.categoryService=categoryService;
        this.previusFrame = previusFrame;
        initiazeTable();
        loadAllProducts();
    }

    private void loadAllProducts() {
        try {
            initiazeTable();
            products = productService.findAllProducts();
            DefaultTableModel model = (DefaultTableModel) jTblProductos.getModel();
            Object rowData[] = new Object[7];
        for(int i = 0; i < products.size();i++){
            rowData[0] = products.get(i).getId();
            rowData[1] = products.get(i).getName();
            rowData[2] = products.get(i).getDescription();
            rowData[3] = products.get(i).obtenerCategoriasConFormato();
            rowData[4] = products.get(i).getStock();
            rowData[5] = products.get(i).getPrice();
            model.addRow(rowData);
        } 
        } catch (Exception ex) {
            Logger.getLogger(ListaProductosGUI.class.getName()).log(Level.SEVERE, "Error al cargar platos", ex);
        }
    }
    private void initiazeTable(){
        jTblProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "idProducto","name","description","Category","stock","price"
                }
        ){
            //Hace que la tabla no se pueda editar(que al presionar eliminar o modificar no salga la direccion del Boton)
            public boolean isCellEditable(int row,int column){
                return false;
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jPnlCentral = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jPnlBotonNuevoProducto = new javax.swing.JPanel();
        btnNuevoProducto = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(1000, 500));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Hyun Seda <br>Productos</html>");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPnlCentral.setLayout(new java.awt.BorderLayout());

        btnAtras.setText("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(120, 48));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPnlCentral.add(btnAtras, java.awt.BorderLayout.LINE_END);

        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.setPreferredSize(new java.awt.Dimension(200, 48));
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotonNuevoProductoLayout = new javax.swing.GroupLayout(jPnlBotonNuevoProducto);
        jPnlBotonNuevoProducto.setLayout(jPnlBotonNuevoProductoLayout);
        jPnlBotonNuevoProductoLayout.setHorizontalGroup(
            jPnlBotonNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(jPnlBotonNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnlBotonNuevoProductoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPnlBotonNuevoProductoLayout.setVerticalGroup(
            jPnlBotonNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(jPnlBotonNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnlBotonNuevoProductoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPnlCentral.add(jPnlBotonNuevoProducto, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPnlCentral, java.awt.BorderLayout.PAGE_END);

        pnlCentral.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Productos existentes:");
        pnlCentral.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        pnlTabla.setLayout(new java.awt.GridBagLayout());

        jTblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblProductos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 800;
        gridBagConstraints.ipady = 250;
        pnlTabla.add(jScrollPane1, gridBagConstraints);

        pnlCentral.add(pnlTabla, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        previusFrame.setVisible(true);
        previusFrame.toFront(); // Traer el MainFrame al frente
        previusFrame.requestFocus(); // Pedir el enfoque para el MainFrame
        // Cerrar el SecondFrame
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        AgregarProductoGUI agregarProductoGUI = new AgregarProductoGUI(categoryService, productService);
        agregarProductoGUI.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPnlBotonNuevoProducto;
    private javax.swing.JPanel jPnlCentral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblProductos;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlTabla;
    // End of variables declaration//GEN-END:variables
}
