/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.OrderService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.ShoppingCartService;
import co.com.hyunseda.market.service.UserService;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class LoginGUI extends javax.swing.JFrame {

    ProductService productService;
    CategoryService categoryService;
    OrderService orderService;
    UserService userService;
    JFrame previusFrame;
    
    public LoginGUI(CategoryService categoryService,ProductService productService, OrderService orderService,
        UserService userService, JFrame previusFrame) {
        initComponents();
        setSize(1000, 500);
        setLocationRelativeTo(null);
        this.productService = productService;
        this.categoryService=categoryService;
        this.orderService = orderService;
        this.userService = userService;
        this.previusFrame = previusFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPnlBackground = new javax.swing.JPanel();
        jPnlTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPnlBottom = new javax.swing.JPanel();
        jBtnIniciarSesion1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 500));

        jPnlBackground.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Hyun Seda <br>Inicio Sesion</html>");
        jPnlTop.add(jLabel2);

        jPnlBackground.add(jPnlTop, java.awt.BorderLayout.PAGE_START);

        jPnlBottom.setLayout(new java.awt.BorderLayout());

        jBtnIniciarSesion1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jBtnIniciarSesion1.setText("Atras");
        jBtnIniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIniciarSesion1ActionPerformed(evt);
            }
        });
        jPnlBottom.add(jBtnIniciarSesion1, java.awt.BorderLayout.LINE_END);

        jPnlBackground.add(jPnlBottom, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtEmail.setPreferredSize(new java.awt.Dimension(120, 22));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 9;
        jPanel1.add(txtEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 9;
        jPanel1.add(txtContrasenia, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jBtnIniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jBtnIniciarSesion.setText("Iniciar sesión");
        jBtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel1.add(jBtnIniciarSesion, gridBagConstraints);

        jPnlBackground.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jBtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIniciarSesionActionPerformed
        String token=null;
        try {
            token=userService.Login(txtEmail.getText(), txtContrasenia.getText());
        } catch (IOException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            if (token != null) {
        // Oculta la ventana de login actual
        this.setVisible(false);
        
        // Crea y muestra el nuevo frame del Dashboard
        DashBoardGUI frame = new DashBoardGUI(categoryService, productService, orderService, userService, this);
        frame.setVisible(true);
    } else {
        // Opcional: Mostrar un mensaje de error si el token es nulo (fallo de login)
        JOptionPane.showMessageDialog(this, "Error: Email o contraseña incorrectos", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jBtnIniciarSesionActionPerformed

    private void jBtnIniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIniciarSesion1ActionPerformed
        previusFrame.setVisible(true);
        previusFrame.toFront(); // Traer el MainFrame al frente
        previusFrame.requestFocus(); // Pedir el enfoque para el MainFrame
        // Cerrar el SecondFrame
        dispose();
    }//GEN-LAST:event_jBtnIniciarSesion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIniciarSesion;
    private javax.swing.JButton jBtnIniciarSesion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlBackground;
    private javax.swing.JPanel jPnlBottom;
    private javax.swing.JPanel jPnlTop;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
